services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_hotel_agent
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - ./n8n_data:/home/node/.n8n

  evolution_api:
    # Usamos la oficial pero con una versión estable
    image: evolutionapi/evolution-api:v1.8.2
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTH_AUTHENTICATION_API_KEY=Balandu2026*
      - AUTH_AUTHENTICATION_GLOBAL_API_KEY=Balandu2026*
      - SERVER_URL=http://localhost:8080
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  n8n_data:
  evolution_instances: